# Generated by Django 3.1.5 on 2021-01-12 11:00

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to=store.models.get_product_upload_address)),
            ],
        ),
    ]
